spring:
  shardingsphere:
    datasource:
      names: ds0,ds1
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/tmy
        username: root
        password: 123456
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/tmy1
        username: root
        password: 123456
    sharding:
      default-database-strategy:
        standard:
          sharding-column: order_no
          precise-algorithm-class-name: com.example.demo.customalgorithm.OrderNoShardingAlgorithm
      tables:
        tb_order:
          actual-data-nodes: ds$->{0..1}.tb_order_taobao, ds$->{0..1}.tb_order_aliyun, ds$->{0..1}.tb_order_tmall
          table-strategy:
            standard:
              sharding-column: merchant
              precise-algorithm-class-name: com.example.demo.customalgorithm.OrderShardingAlgorithm
    props:
      sql:
        show: true