spring:
  shardingsphere:
    datasource:
      names: ds0,ds1
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/tmy
        username: root
        password: 123456
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/tmy1
        username: root
        password: 123456
    sharding:
      tables:
        tb_order:
          actual-data-nodes: ds$->{0..1}.tb_order_$->{0..1}
          database-strategy:
            hint:
              algorithm-class-name: com.example.demo.customalgorithm.OrderHintShardingAlgorithm
          table-strategy:
            hint:
              algorithm-class-name:  com.example.demo.customalgorithm.OrderHintShardingAlgorithm
          key-generator:
            type: SNOWFLAKE
            column: id
            props:
              worker.id: 123
    props:
      sql:
        show: false